name: Build
on:
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Build
      run:
        pip install --upgrade pip setuptools wheel
        python setup.py bdist_wheel
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/PyLoggo-0.0.1-py3-none-any.whl